import React from 'react';

const ManListOptions = () => (<datalist id="ManListOptions">
     <option value="cruise bench 20 s115hp" />
     <option value="cruise bench 20 s150hp" />
     <option value="cruise bench 22 s115hp" />
     <option value="cruise bench 22 s150hp" />
     <option value="cruise switchback 22 s115hp" />
     <option value="cruise switchback 22 s150hp" />
     <option value="cruise switchback 24 s115hp" />
     <option value="cruise switchback 24 s150hp" />
     <option value="explore bench 22" />
     <option value="explore bench 22 trifold bench" />
     <option value="explore bench 22 s115hp" />
     <option value="explore bench 22 s115hp trifold bench" />
     <option value="explore bench 22 s150hp" />
     <option value="explore bench 22 s150hp trifold bench" />
     <option value="explore navigator 22 trifold bench" />
     <option value="explore navigator 22 s115hp trifold bench" />
     <option value="explore navigator 22 s150hp trifold bench" />
     <option value="explore navigator 24 25x27x25 trifold bench" />
     <option value="explore navigator 24 dual motor trifold bench" />
     <option value="explore navigator 24 trifold bench" />
     <option value="explore navigator 24 s115hp trifold bench" />
     <option value="explore navigator 24 s150hp trifold bench" />
     <option value="explore navigator 26 25x27x25 trifold bench" />
     <option value="explore navigator 26 dual motor trifold bench" />
     <option value="explore navigator 26 s115hp trifold bench" />
     <option value="explore navigator 26 s150hp trifold bench" />
     <option value="explore switchback 22 trifold bench" />
     <option value="explore switchback 22 s115hp trifold bench" />
     <option value="explore switchback 22 s150hp trifold bench" />
     <option value="explore switchback 24 25x27x25 trifold bench" />
     <option value="explore switchback 24 dual motor trifold bench" />
     <option value="explore switchback 24 trifold bench" />
     <option value="explore switchback 24 s115hp trifold bench" />
     <option value="explore switchback 24 s150hp trifold bench" />
     <option value="explore switchback 26 25x27x25 trifold bench" />
     <option value="explore switchback 26 dual motor trifold bench" />
     <option value="explore switchback 26 s115hp trifold bench" />
     <option value="explore switchback 26 s150hp trifold bench" />
     <option value="lx rfx 23" />
     <option value="lx rfx 23" />
     <option value="lx rfx 23" />
     <option value="lx rfx 23 dual motor" />
     <option value="lx rfx 23 dual motor" />
     <option value="lx rfx 23 dual motor" />
     <option value="lx rfx 25" />
     <option value="lx rfx 25" />
     <option value="lx rfx 25" />
     <option value="lx rfx 25 dual motor" />
     <option value="lx rfx 25 dual motor" />
     <option value="lx rfx 25 dual motor" />
     <option value="lx rfx 27" />
     <option value="lx rfx 27" />
     <option value="lx rfx 27" />
     <option value="lx rfx 27 dual motor" />
     <option value="lx rfx 27 dual motor" />
     <option value="lx rfx 27 dual motor" />
     <option value="lx rfxw 23" />
     <option value="lx rfxw 23" />
     <option value="lx rfxw 23" />
     <option value="lx rfxw 23 dual motor" />
     <option value="lx rfxw 23 dual motor" />
     <option value="lx rfxw 23 dual motor" />
     <option value="lx rfxw 25" />
     <option value="lx rfxw 25" />
     <option value="lx rfxw 25" />
     <option value="lx rfxw 25 dual motor" />
     <option value="lx rfxw 25 dual motor" />
     <option value="lx rfxw 25 dual motor" />
     <option value="lx rfxw 27" />
     <option value="lx rfxw 27" />
     <option value="lx rfxw 27" />
     <option value="lx rfxw 27 dual motor" />
     <option value="lx rfxw 27 dual motor" />
     <option value="lx rfxw 27 dual motor" />
     <option value="lx srs 23" />
     <option value="lx srs 23" />
     <option value="lx srs 23" />
     <option value="lx srs 23 dual motor" />
     <option value="lx srs 23 dual motor" />
     <option value="lx srs 23 dual motor" />
     <option value="lx srs 25" />
     <option value="lx srs 25" />
     <option value="lx srs 25" />
     <option value="lx srs 25 dual motor" />
     <option value="lx srs 25 dual motor" />
     <option value="lx srs 25 dual motor" />
     <option value="lx srs 27" />
     <option value="lx srs 27" />
     <option value="lx srs 27" />
     <option value="lx srs 27 dual motor" />
     <option value="lx srs 27 dual motor" />
     <option value="lx srs 27 dual motor" />
     <option value="lx srw 23" />
     <option value="lx srw 23" />
     <option value="lx srw 23" />
     <option value="lx srw 23 dual motor" />
     <option value="lx srw 23 dual motor" />
     <option value="lx srw 23 dual motor" />
     <option value="lx srw 25" />
     <option value="lx srw 25" />
     <option value="lx srw 25" />
     <option value="lx srw 25 dual motor" />
     <option value="lx srw 25 dual motor" />
     <option value="lx srw 25 dual motor" />
     <option value="lx srw 27" />
     <option value="lx srw 27" />
     <option value="lx srw 27" />
     <option value="lx srw 27 dual motor" />
     <option value="lx srw 27 dual motor" />
     <option value="lx srw 27 dual motor" />
     <option value="xt rfx 23" />
     <option value="xt rfx 23" />
     <option value="xt rfx 23 dual motor" />
     <option value="xt rfx 23 dual motor" />
     <option value="xt rfx 25" />
     <option value="xt rfx 25" />
     <option value="xt rfx 25 dual motor" />
     <option value="xt rfx 25 dual motor" />
     <option value="xt rfx 27" />
     <option value="xt rfx 27" />
     <option value="xt rfx 27 dual motor" />
     <option value="xt rfx 27 dual motor" />
     <option value="xt rfxw 23" />
     <option value="xt rfxw 23" />
     <option value="xt rfxw 23 dual motor" />
     <option value="xt rfxw 23 dual motor" />
     <option value="xt rfxw 25" />
     <option value="xt rfxw 25" />
     <option value="xt rfxw 25 dual motor" />
     <option value="xt rfxw 25 dual motor" />
     <option value="xt rfxw 27" />
     <option value="xt rfxw 27" />
     <option value="xt rfxw 27 dual motor" />
     <option value="xt rfxw 27 dual motor" />
     <option value="xt srs 23" />
     <option value="xt srs 23" />
     <option value="xt srs 23 dual motor" />
     <option value="xt srs 23 dual motor" />
     <option value="xt srs 25" />
     <option value="xt srs 25" />
     <option value="xt srs 25 dual motor" />
     <option value="xt srs 25 dual motor" />
     <option value="xt srs 27" />
     <option value="xt srs 27" />
     <option value="xt srs 27 dual motor" />
     <option value="xt srs 27 dual motor" />
     <option value="xt srw 23" />
     <option value="xt srw 23" />
     <option value="xt srw 23 dual motor" />
     <option value="xt srw 23 dual motor" />
     <option value="xt srw 25" />
     <option value="xt srw 25" />
     <option value="xt srw 25 dual motor" />
     <option value="xt srw 25 dual motor" />
     <option value="xt srw 27" />
     <option value="xt srw 27" />
     <option value="xt srw 27 dual motor" />
     <option value="xt srw 27 dual motor" />
</datalist>
)
export default ManListOptions;


