import React from 'react';

const SwitchlistOptions = () => (<datalist id="SwitchlistOptions">
      <option value="switch sport 21' 230hp neon yellow (new catalyst) 51pk" />
      <option value="switch sport 21' 230hp neon yellow 48pc" />
      <option value="switch sport 21' 230hp lava red (new catalyst) 51pm" />
      <option value="switch sport 21' 230hp lava red 48pd" />
      <option value="switch sport 21' 230hp carribean blue (new catalyst) 51ph" />
      <option value="switch sport 21' 230hp carribean blue 48pb" />
      <option value="switch sport 21' 230hp neon yellow (new catalyst) 51pj" />
      <option value="switch sport 21' 230hp neon yellow 47pr" />
      <option value="switch sport 21' 230hp lava red (new catalyst) 51pl" />
      <option value="switch sport 21' 230hp lava red 47pt" />
      <option value="switch sport 21' 230hp carribean blue (new catalyst) 51pg" />
      <option value="switch sport 21' 230hp carribean blue 47pp" />
      <option value="switch sport 18' 230hp neon yellow (new catalyst) 51pd" />
      <option value="switch sport 18' 230hp neon yellow 47pz" />
      <option value="switch sport 18' 230hp lava red (new catalyst) 51pf" />
      <option value="switch sport 18' 230hp lava red 48pa" />
      <option value="switch sport 18' 230hp carribean blue (new catalyst) 51pb" />
      <option value="switch sport 18' 230hp carribean blue 47py" />
      <option value="switch sport 18' 230hp neon yellow (new catalyst) 51pc" />
      <option value="switch sport 18' 230hp neon yellow 47pk" />
      <option value="switch sport 18' 230hp lava red (new catalyst) 51pe" />
      <option value="switch sport 18' 230hp lava red 47pm" />
      <option value="switch sport 18' 230hp carribean blue (new catalyst) 51pa" />
      <option value="switch sport 18' 230hp carribean blue 47ph" />
      <option value="switch sport compact 170hp neon yellow 48pw" />
      <option value="switch sport compact 170hp lava red 47px" />
      <option value="switch sport compact 170hp carribean blue 47pv" />
      <option value="switch sport compact 170hp neon yellow 47pc" />
      <option value="switch sport compact 170hp lava red 47pe" />
      <option value="switch sport compact 170hp carribean blue 47pa" />
      <option value="switch cruise. 21' 230hp neon yellow (new catalyst) 50pk" />
      <option value="switch cruise. 21' 230hp neon yellow 45pv" />
      <option value="switch cruise. 21' 230hp lava red (new catalyst) 50pm" />
      <option value="switch cruise. 21' 230hp lava red 45pw" />
      <option value="switch cruise. 21' 230hp carribean blue (new catalyst) 50ph" />
      <option value="switch cruise. 21' 230hp carribean blue 45pu" />
      <option value="switch cruise. 21' 230hp neon yellow (new catalyst) 50pj" />
      <option value="switch cruise. 21' 230hp neon yellow 46pr" />
      <option value="switch cruise. 21' 230hp lava red (new catalyst) 50pl" />
      <option value="switch cruise. 21' 230hp lava red 46pt" />
      <option value="switch cruise. 21' 230hp carribean blue (new catalyst) 50pg" />
      <option value="switch cruise. 21' 230hp carribean blue 46pp" />
      <option value="switch cruise 21' 170hp neon yellow 45ps" />
      <option value="switch cruise 21' 170hp lava red 45pt" />
      <option value="switch cruise 21' 170hp carribean blue 45pr" />
      <option value="switch cruise 21' 170hp neon yellow 46pm" />
      <option value="switch cruise 21' 170hp lava red 46pn" />
      <option value="switch cruise 21' 170hp carribean blue 46pl" />
      <option value="switch cruise 18' 230hp neon yellow (new catalyst) 50pd" />
      <option value="switch cruise 18' 230hp neon yellow 45pm" />
      <option value="switch cruise 18' 230hp lava red (new catalyst) 50pf" />
      <option value="switch cruise 18' 230hp lava red 45pq" />
      <option value="switch cruise 18' 230hp carribean blue (new catalyst) 50pb" />
      <option value="switch cruise 18' 230hp carribean blue 45pj" />
      <option value="switch cruise 18' 230hp neon yellow (new catalyst) 50pc" />
      <option value="switch cruise 18' 230hp neon yellow 45pl" />
      <option value="switch cruise 18' 230hp lava red (new catalyst) 50pe" />
      <option value="switch cruise 18' 230hp lava red 45pp" />
      <option value="switch cruise 18' 230hp carribean blue (new catalyst) 50pa" />
      <option value="switch cruise 18' 230hp carribean blue 45ph" />
      <option value="switch cruise 18' 170hp neon yellow 46pz" />
      <option value="switch cruise 18' 170hp lava red 45pg" />
      <option value="switch cruise 18' 170hp carribean blue 46py" />
      <option value="switch cruise 18' 170hp neon yellow 46pf" />
      <option value="switch cruise 18' 170hp lava red 46pj" />
      <option value="switch cruise 18' 170hp carribean blue 46pd" />
      <option value="switch cruise 18' 130hp neon yellow 46pw" />
      <option value="switch cruise 18' 130hp lava red 46px" />
      <option value="switch cruise 18' 130hp carribean blue 46pv" />
      <option value="switch cruise 18' 130hp neon yellow 46pb" />
      <option value="switch cruise 18' 130hp lava red 46pc" />
      <option value="switch cruise 18' 130hp carribean blue 46pa" />
      <option value="switch 16' 130hp carribean blue 41pp" />
      <option value="switch 16' 130hp  41pk" />
      <option value="switch compact 130hp carribean blue 41pn" />
      <option value="switch compact 130hp  41pj" />
      <option value="switch 19' 170hp carribean blue 41pq" />
      <option value="switch 19' 170hp  41pl" />
</datalist>
)
export default SwitchlistOptions;